FROM golang:1.20

WORKDIR /app

# Copy the module files first and download dependencies for caching
COPY go.mod go.sum ./
RUN go mod download

# Now copy the rest of your application's code
COPY . .

CMD ["go", "run", "main.go"]
