apiVersion: v1
kind: Pod
metadata:
  name: access-azure-resources
  labels:
    azure.workload.identity/use: "true"
spec:
  containers:
  - name: workloadidentity
    image: mohatb/workloadidentitytest:latest
    env:
    - name: AZURE_SUBSCRIPTION_ID
      value: "f0f3c44a-153b-4349-9d6c-6c30282d78cd"
    - name: AZURE_RESOURCE_GROUP
      value: "gitops"
  serviceAccountName: workload-identity-sa
  volumes:
  - name: test-token
    projected:
      sources:
      - serviceAccountToken:
          path: test-token
          expirationSeconds: 3600
          audience: test