apiVersion: v1
kind: Pod
metadata:
  name: access-azure-resources
  labels:
    azure.workload.identity/use: "true"
spec:
  containers:
  - name: workloadidentity
    image: mohatb/workloadidentitytest:latest
    env:
    - name: AZURE_SUBSCRIPTION_ID
      value: "<subscription ID>"
    - name: AZURE_RESOURCE_GROUP
      value: "<resource group>"
  serviceAccountName: workload-identity-sa
  volumes:
  - name: test-token
    projected:
      sources:
      - serviceAccountToken:
          path: test-token
          expirationSeconds: 3600
          audience: test